version: '3.8'

services:
  hardhat:
    build:
      context: .
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    user: "${USER_ID}:${GROUP_ID}" # ユーザーIDとグループIDを環境変数から取得    
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
      - node_cache:/tmp/.cache # tmpディレクトリにマウント
    ports:
      - "8545:8545" # Hardhatのデフォルトポート
    environment:
      - NODE_ENV=development
    command: npx hardhat node --hostname 0.0.0.0 # Hardhatノードを直接起動
    networks:
      - blockchain-network
    hostname: hardhat
    container_name: erc1056-hardhat

  integration-tests:
    build:
      context: .
      dockerfile: integration-tests/Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./integration-tests:/app
      - ./integration-tests/node_modules:/app/node_modules
      - ./artifacts:/app/artifacts
      - integration_node_cache:/tmp/.cache # tmpディレクトリにマウント
    environment:
      - NODE_ENV=development
      - BLOCKCHAIN_URL=http://hardhat:8545
      - TEST_PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
    depends_on:
      - hardhat
    networks:
      - blockchain-network
    extra_hosts:
      - "hardhat:172.17.0.1" # Dockerホストへのアクセス
    command: /bin/sh -c "chmod +x /app/run-tests.sh && /app/run-tests.sh"

networks:
  blockchain-network:
    driver: bridge

volumes:
  node_cache:
  integration_node_cache:
